source "https://rubygems.org"
#gemspec
gem 'orientdb' , :path => '/home/topo/orientdb-jruby' , :platforms => :jruby

gem 'active-orient' , :path => '/home/topo/activeorient'


group :development, :test do
	gem "awesome_print"
	gem "rspec"
	gem 'rspec-legacy_formatters'
	gem 'rspec-its'
	gem 'rspec-collection_matchers'
	gem 'rspec-context-private'
	gem 'guard-jruby-rspec', :platforms => :jruby, :git => 'git://github.com/jkutner/guard-jruby-rspec.git'
	gem 'guard'#, :platforms => :ruby
	gem 'guard-rspec'
##	gem 'database_cleaner'
	gem 'rb-inotify'
	gem 'pry'
end
